platform :ios, "10.0"
# https://github.com/facebook/react-native/issues/30002#issuecomment-696594433
source "https://github.com/CocoaPods/Specs.git"
# source 'https://cdn.cocoapods.org/'
require_relative "../../node_modules/@react-native-community/cli-platform-ios/native_modules"
require_relative "../../node_modules/react-native/scripts/react_native_pods"

target "example" do
  use_react_native!(:path => "../../node_modules/react-native")

  pod "react-native-month-year-picker", :path => "../../react-native-month-year-picker.podspec"

  target "exampleTests" do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target "example-tvOS" do
  # Pods for example-tvOS

  target "example-tvOSTests" do
    inherit! :search_paths
    # Pods for testing
  end
end
