platform :ios, "10.0"
# https://github.com/facebook/react-native/issues/30002#issuecomment-696594433
source "https://github.com/CocoaPods/Specs.git"
# source 'https://cdn.cocoapods.org/'
require_relative "../../node_modules/@react-native-community/cli-platform-ios/native_modules"
require_relative "../../node_modules/react-native/scripts/react_native_pods"

target "example" do
  use_react_native!(
    :path => "../../node_modules/react-native",
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod "react-native-month-year-picker", :path => "../../react-native-month-year-picker.podspec"

  target "exampleTests" do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
